### ISSUE TITLE
file:// URIs

### ISSUE THREAD

**Issue by hacker1024** [Baseflow/flutter_cached_network_image#311]
The plugin should be able to handle local `file://` URIs, and display them (without caching, as they're local).

**Comment by renefloor** [comment]
@hacker1024 Why would you use CachedNetworkImage in that case if you could use FileImage directly? If you do want some of the caching logic you can also put the file into the cache yourself: https://pub.dev/documentation/flutter_cache_manager/latest/flutter_cache_manager/BaseCacheManager/putFile.html

The putFile method takes at least an url and the filebytes, but you can also specify when the file should be updated again.

**Comment by clragon** [comment]
this would be kinda useful in cases where you get either a network or a local image and you dont want to check for which one it is.
but I assume this just moves the check inside the network image, so we might as well not.

**Comment by clragon** [comment]
this would actually be useful in my case, where an image could be from the internet or a local image.
since cached network image provides animations and error + loading builder, it would make sense to use it instead of a FileImage maybe?

it would also remove the need to pass different widgets and check for local files manually.
