### ISSUE TITLE
[web] not working

### ISSUE THREAD

**Issue by deakjahn** [Baseflow/flutter_cached_network_image#386]
## 🐛 Bug Report

`CachedNetworkImage`, when used directly (not building with the provider) doesn't work in a Flutter Web application. No error, just nothing displays. The provider isn't called at all unless specifically used, so there seems to be nothing web-specific in the code in this case.

### Expected behavior

Image displayed.

### Thoughts

I'm not really sure this approach with conditional imports, with all three classes having exactly the same name is really feasible. I very well see that you're not really keen on turning such a simple plugin into a federated one but, well, I'm not sure. :-)

**Comment by renefloor** [comment]
As already said in the readme and in #303 the web support is currently only available for the imageprovider and not for the imagewidget.

The widget doesn't use the imageprovider, but it uses FileImage as it does all the loading logic separately from the imageprovider. At the time the widget was made that was needed because there weren't enough options to listen to the imageprovider results. Now the imageprovider does support all those cases and therefore the Image widget could be rewritten.

As the imageloading logic is much simpler now and independent of the caching I released [OctoImage](https://pub.dev/packages/octo_image) which has almost the exact same behaviour as the CachedNetworkImage widget.

At this moment I'm working on the `gaplessPlayback` of OctoImage boolean to work the same as `useOldImageOnUrlChange` of CachedNetworkImage. Currently the OctoImage doesn't fade from one image to the next. When that is fixed I can replace all the logic in CachedNetworkImage widget with OctoImage without any breaking change.

How that will work you can already see in this branch: https://github.com/Baseflow/flutter_cached_network_image/blob/feature/octo_image/lib/src/cached_image_widget.dart

For tracking web support there is already ticket #303 so I'll close this one. You can already just use OctoImage with the CachedNetworkImageProvider if you want.

**Comment by deakjahn** [comment]
Well, OK. I started to check it out and I seem to like it. I'd be vary to start using something with so low a version number so it's a good thing you mentioned. :-)

Is there any plan to consolidate the whole in the end?

**Comment by renefloor** [comment]
I think it will stay like in that branch. OctoImage has all the logic for placeholders and fading, CachedNetworkImage is just a wrapper that takes an url and passes an ImageProvider to OctoImage

**Comment by deakjahn** [comment]
At the moment I'll go on with this, it works on both platforms now. That new blur functionality is mighty tempting, I might need to modify our workflow to accommodate that.

Thanks.

**Comment by deakjahn** [comment]
By the way, I saw you added the provider extension to the BlurHash package. Don't you want to rework it a little bit? :-) There is no need to depend on the `image` package, all that simple functionality is readily available in the framework `dart:ui`. Wait a minute, I copy the relevant part here from a prvoder of mine so that you don't need to find out:

    import 'dart:ui' as skia;

    final completer = Completer<skia.Image>();
    skia.decodeImageFromPixels(bytes, width, height, skia.PixelFormat.rgba8888, (image) {
      completer.complete(image);
    });
    return completer.future;

Actually, this is just the same they use in the main part of the package. This is already enough to put into an image provider `_loadAsync` but if you ever want to create a PNG out of it, that goes as well:

    final png = await image.toByteData(format: skia.ImageByteFormat.png);

**Comment by renefloor** [comment]
Thanks for the tip @deakjahn. I'd appreciate it if you'd open an issue in the blurhash git or even make a PR with your suggested changes.

**Comment by deakjahn** [comment]
OK, I can, just that I didn't want to take away your credit. :-)

**Comment by renefloor** [comment]
@deakjahn I just made a simple imageprovider, you don't take away any credit from me. You also should take your credit on the work you just did ;)

**Comment by shreyash333** [comment]
@deakjahn @renefloor i have used CachedNetworkImage with CarouselSlider to display image, its working proper in Andriod and IOS but Web its showing errorwidget. 

here is the code

CachedNetworkImage(
imageUrl: 'https://www.fotolip.com/wp-content/uploads/2016/05/Certificate-Templates-4.jpg',
placeholder: (context, url) => Center( child: CircularProgressIndicator(),),
errorWidget: (context, url, error) => Icon(Icons.error),
),
