### ISSUE TITLE
[BETA] Error when scrolling to fast

### ISSUE THREAD

**Issue by fryette** [Baseflow/flutter_cached_network_image#400]
## 🐛 Bug Report

I see log with:
```
setState() called after dispose(): _ImageState#7657b(lifecycle state: defunct, not mounted, stream: ImageStream#add3c(MultiFrameImageStreamCompleter#a18ad, [200×200] @ 1.0x, 1 listener), pixels: null, loadingProgress: null, frameNumber: null, wasSynchronouslyLoaded: false)

The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().

When the exception was thrown, this was the stack
#0      State.setState.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1197
#1      State.setState 
package:flutter/…/widgets/framework.dart:1232
#2      _ImageState._getListener.<anonymous closure> 
package:flutter/…/widgets/image.dart:1131
#3      ImageStreamCompleter.reportError 
package:flutter/…/painting/image_stream.dart:504
#4      ImageStreamCompleter.setImage 
package:flutter/…/painting/image_stream.dart:439
```
...
═══════

### Expected behavior
Should be handled appropriately 

### Reproduction steps
I have a list with an images and when I try to scroll fast some of the images not loaded

### Configuration

**Version:** 2.3.0-beta

**Platform:** 
- [ ] :iphone: iOS - not tested
- [x ] :robot: Android

**Comment by renefloor** [comment]
Yes that is a known issue. Also reported here: https://github.com/Baseflow/octo_image/issues/1
It is a bug in the Flutter Image itself when using errorlisteners. This PR fixes it: https://github.com/flutter/flutter/pull/57201
I will set a minimum Flutter version on this package before 2.3.0 hits stable, but there hasn't even been a dev release since I fixed this issue.

So for now I would recommend either don't use errorListeners in lists, don't scroll fast or go back tot 2.2.0. You could also switch to Flutter master channel, but that is not recommended.
