### ISSUE TITLE
CachedNetworkImageProvider is kind of useless

### ISSUE THREAD

**Issue by nicolasvahidzein** [Baseflow/flutter_cached_network_image#412]
Hello, i really like this package but i'm confused aboutsomething: i can never find a widget that uses CachedNetworkImage, it is incompatible everytime i try to use it. The only i can use is CachedNetworkImageProvider and that one has no options so i can show a preloader. What is the point? 

I'm trying to use it inside a DecorationImage but no luck.

**Comment by renefloor** [comment]
First of all, something isn't useless when it doesn't exactly what you want when it helps others.

An ImageProvider is exactly what the name says, it provides an image. All of these other widgets that show an image, such as DecorationImage, need an ImageProvider to show that image. ImageProviders are not widgets, so they can't show placeholders or things like that.

CachedNetworkImage is the widget that does things like showing placeholders and loading the image, but you can't give that directly to the DecorationImage because it is a widget, not just an image.

However, as you can see in the Readme of this package you can use a callback for when the image is loaded and manipulate the image. This is from the readme
```
CachedNetworkImage(
  imageUrl: "http://via.placeholder.com/200x150",
  imageBuilder: (context, imageProvider) => Container(
    decoration: BoxDecoration(
      image: DecorationImage(
          image: imageProvider,
          fit: BoxFit.cover,
          colorFilter:
              ColorFilter.mode(Colors.red, BlendMode.colorBurn)),
    ),
  ),
  placeholder: (context, url) => CircularProgressIndicator(),
  errorWidget: (context, url, error) => Icon(Icons.error),
),
```

**Comment by nicolasvahidzein** [comment]
Thank you for your reply. Sorry about my tone, i was quite frustrated. I decided to go about it another way and i decided to instead of using it as a decoration to just use it as a proper widget and use stack. Is there a way to know when it is completely loaded and if there was an error because on timeout that widget will never load the proper image, it's quite a problem.
