### ISSUE TITLE
Skia OctoImage + 2.3.0-beta+1 - Unable to get image to load

### ISSUE THREAD

**Issue by m-j-g** [Baseflow/flutter_cached_network_image#422]
I'm not sure if I just haven't hit the magic combination or if this is a feature request to support something unimplemented.

I've been trying desperately to get a network image to show up on web using FLUTTER_WEB_USE_SKIA=true.  I brought in the OctoImage library and am using 2.3.0-beta+1 of CachedNetwork Image.  I have been playing with various things, but have yet to get a network image to show up on web.  I tried bother render methods for web as well.  Any pointers or guidance as to how I can get a network image to show up on web would be greatly appreciated.

```
OctoImage(
            image: CachedNetworkImageProvider(imageURL,
                         imageRenderMethodForWeb: ImageRenderMethodForWeb.HttpGet,),
            fadeInDuration: Duration(milliseconds: 300),
            width: 100,
            height: 100,
            )
```

**Comment by renefloor** [comment]
When I use ImageRenderMethodForWeb.HttpGet the library works for me with SKIA enabled. (Note this flag is added in 2.3.0-rc.)

What might your problem is that you have to make sure CORS headers are correctly set. This depends on images per host. Problem is that in debug mode it is per definition running on localhost so all images are from another domain. It also depends on the server settings it seems. In the example projects some work and some don't.

This one doesn't work: http://via.placeholder.com/350x150
This one works: https://images.unsplash.com/photo-1532264523420-881a47db012d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9

You could try the last one to check if the image is shown in your project using SKIA.

**Comment by m-j-g** [comment]
ohhhh, thanks for taking the time to explain @renefloor .  For anyone using firebase storage, following the CORS Configuration section here > https://firebase.google.com/docs/storage/web/download-files along with the flag that @renefloor mentioned above will allow the images to load on Skia.
