### ISSUE TITLE
Building flutter web project failed

### ISSUE THREAD

**Issue by ritvij-saxena** [Baseflow/flutter_cached_network_image#447]
> Target dart2js failed: Exception:
> /D:/Flutter%20Course/flutter_windows_v1.0.0-stable/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-2.2.0+1/lib/src/image_provider/_image_provider_web.dart:103:9:
> Error: No named parameter with the name 'chunkCallback'.
>         chunkCallback: (int bytes, int total) {
>         ^^^^^^^^^^^^^
> /D:/Flutter%20Course/flutter_windows_v1.0.0-stable/flutter/bin/cache/flutter_web_sdk/lib/ui/src/ui/painting.dart:1606:15:
> Info: Found this candidate, but the arguments don't match.
> Future<Codec> webOnlyInstantiateImageCodecFromUrl(Uri uri) {
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Error: Compilation failed.
> 
> 
> Compiling lib\main.dart for the Web...                             11.3s
> Exception: Failed to compile application for the Web.

**flutter doctor -v**

> D:\AndroidProjects\ojaexpress\ojaexpress_flutter>flutter doctor -v
> [√] Flutter (Channel master, v1.15.4-pre.51, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
>     • Flutter version 1.15.4-pre.51 at D:\Flutter Course\flutter_windows_v1.0.0-stable\flutter
>     • Framework revision dc636069fc (6 months ago), 2020-02-12 22:22:49 -0800
>     • Engine revision e0ebaea590
>     • Dart version 2.8.0 (build 2.8.0-dev.9.0 e4c39721c4)
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\ritvi\AppData\Local\Android\Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: D:\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at D:\Android Studio
>     • Flutter plugin version 48.0.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [!] IntelliJ IDEA Community Edition (version 2019.3)
>     • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [!] VS Code (version 1.48.1)
>     • VS Code at C:\Users\ritvi\AppData\Local\Programs\Microsoft VS Code
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (3 available)
>     • AOSP on IA Emulator • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
>     • Chrome              • chrome        • web-javascript • Google Chrome 84.0.4147.135
>     • Web Server          • web-server    • web-javascript • Flutter Tools
> 
> ! Doctor found issues in 2 categories.
> 
> 

Any assistance would be appreciated

**Comment by renefloor** [comment]
Can you update Flutter to 1.17, the latest stable?

**Comment by ritvij-saxena** [comment]
The problem still persists. Can this library be used for web projects as well?

**Comment by danielroek** [comment]
Hi @ritvij-saxena ,

Could you please provide us with some more info on the errors you are getting with the latest flutter beta version? Web support is not yet available on Flutter's stable branch. 
To go to the beta channel run `flutter channel beta` and `flutter upgrade`.

**Comment by ritvij-saxena** [comment]
When I run the app on the Chrome web with the cached_network_image package, it gives a blank screen. However, if I run the app without the package it works as expected.

**Comment by renefloor** [comment]
@ritvij-saxena can you show the output of Flutter doctor again?

**Comment by danielroek** [comment]
Could you please provide us with the output of `flutter run -v` and `flutter doctor -v` with the latest flutter beta version.

**Comment by ritvij-saxena** [comment]
**flutter doctor -v**

> [√] Flutter (Channel master, v1.15.4-pre.51, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
>     • Flutter version 1.15.4-pre.51 at D:\Flutter Course\flutter_windows_v1.0.0-stable\flutter
>     • Framework revision dc636069fc (7 months ago), 2020-02-12 22:22:49 -0800
>     • Engine revision e0ebaea590
>     • Dart version 2.8.0 (build 2.8.0-dev.9.0 e4c39721c4)
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
>     • Android SDK at C:\Users\ritvi\AppData\Local\Android\Sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-30, build-tools 30.0.2
>     • Java binary at: D:\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
>     • All Android licenses accepted.
> 
> [√] Chrome - develop for the web
>     • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
> 
> [√] Android Studio (version 4.0)
>     • Android Studio at D:\Android Studio
>     • Flutter plugin version 48.0.2
>     • Dart plugin version 193.7361
>     • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
> 
> [!] IntelliJ IDEA Community Edition (version 2019.3)
>     • IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
>     X Flutter plugin not installed; this adds Flutter specific functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [!] VS Code (version 1.48.2)
>     • VS Code at C:\Users\ritvi\AppData\Local\Programs\Microsoft VS Code
>     X Flutter extension not installed; install from
>       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
> 
> [√] Connected device (2 available)
>     • Chrome     • chrome     • web-javascript • Google Chrome 85.0.4183.83
>     • Web Server • web-server • web-javascript • Flutter Tools
> 
> ! Doctor found issues in 2 categories.
>

**Comment by danielroek** [comment]
Hi @ritvij-saxena , 

It seems you still run Flutter version 1.15.4. Could you please run `flutter channel beta` `flutter upgrade`  `flutter clean` and after that run `flutter doctor -v` and post the output and than run the project again with `flutter run -v` and post the output if it still doesn't work.

**Comment by fisforfaheem** [comment]
same error for me \



Skip to main content
fisforfaheem's team
awesome-mestorf-058de9
Upgrade




Deploys
Deploy details
Deploy failed
Production: main@b3e8de0. By fisforfaheem on GitHub. Today at 4:33 PM

We couldn’t deploy your site. Check out our Build docs for tips on troubleshooting your build, or ask us for debugging advice.

Deploy settings
Retry deploy
Fancy a game?
This deploy is done, but hey, you can still play if you want to!

Play game
Deploy log



4:33:18 PM: Build ready to start
4:33:21 PM: build-image version: 73def8bb10593b9b818f44989a75ea508018ccb7 (focal)
4:33:21 PM: build-image tag: v4.5.2
4:33:21 PM: buildbot version: e07f38cea73012d29c839c78dec87335277fe704
4:33:21 PM: Fetching cached dependencies
4:33:22 PM: Starting to download cache of 616.1KB
4:33:22 PM: Finished downloading cache in 480.274147ms
4:33:22 PM: Starting to extract cache
4:33:22 PM: Finished extracting cache in 28.973206ms
4:33:22 PM: Finished fetching cache in 510.484633ms
4:33:22 PM: Starting to prepare the repo for build
4:33:22 PM: Preparing Git Reference refs/heads/main
4:33:23 PM: Parsing package.json dependencies
4:33:24 PM: Starting build script
4:33:24 PM: Installing dependencies
4:33:24 PM: Python version set to 2.7
4:33:25 PM: v16.13.1 is already installed.
4:33:26 PM: Now using node v16.13.1 (npm v8.1.2)
4:33:26 PM: Started restoring cached build plugins
4:33:26 PM: Finished restoring cached build plugins
4:33:26 PM: Attempting ruby version 2.7.2, read from environment
4:33:28 PM: Using ruby version 2.7.2
4:33:29 PM: Using PHP version 8.0
4:33:29 PM: Started restoring cached go cache
4:33:29 PM: Finished restoring cached go cache
4:33:29 PM: go version go1.16.5 linux/amd64
4:33:29 PM: go version go1.16.5 linux/amd64
4:33:29 PM: Installing missing commands
4:33:29 PM: Verify run directory
4:33:32 PM: ​
4:33:32 PM: ────────────────────────────────────────────────────────────────
4:33:32 PM:   Netlify Build                                                 
4:33:32 PM: ────────────────────────────────────────────────────────────────
4:33:32 PM: ​
4:33:32 PM: ❯ Version
4:33:32 PM:   @netlify/build 26.0.2
4:33:32 PM: ​
4:33:32 PM: ❯ Flags
4:33:32 PM:   baseRelDir: true
4:33:32 PM:   buildId: 61caf5fe81003a00072844f1
4:33:32 PM:   deployId: 61caf5fe81003a00072844f3
4:33:32 PM: ​
4:33:32 PM: ❯ Current directory
4:33:32 PM:   /opt/build/repo
4:33:32 PM: ​
4:33:32 PM: ❯ Config file
4:33:32 PM:   No config file was defined: using default values.
4:33:32 PM: ​
4:33:32 PM: ❯ Context
4:33:32 PM:   production
4:33:32 PM: ​
4:33:32 PM: ────────────────────────────────────────────────────────────────
4:33:32 PM:   1. Build command from Netlify app                             
4:33:32 PM: ────────────────────────────────────────────────────────────────
4:33:32 PM: ​
4:33:32 PM: $ if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
4:33:32 PM: bash: line 0: cd: flutter: No such file or directory
4:33:32 PM: Cloning into 'flutter'...
4:33:54 PM: Downloading Dart SDK from Flutter engine 01d19ceef477d99102f808e808937efec01579ad...
4:33:54 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
4:33:54 PM:                                  Dload  Upload   Total   Spent    Left  Speed
4:33:55 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
4:33:56 PM:  29  218M   29 64.0M    0     0  68.4M      0  0:00:03 --:--:--  0:00:03 68.4M
4:33:56 PM:  93  218M   93  203M    0     0   110M      0  0:00:01  0:00:01 --:--:--  110M
4:33:56 PM: 100  218M  100  218M    0     0   114M      0  0:00:01  0:00:01 --:--:--  114M
4:34:04 PM: Building flutter tool...
4:34:04 PM: Resolving dependencies...
4:34:06 PM: + _fe_analyzer_shared 31.0.0 (32.0.0 available)
4:34:06 PM: + analyzer 2.8.0 (3.0.0 available)
4:34:06 PM: + archive 3.1.6
4:34:06 PM: + args 2.3.0
4:34:06 PM: + async 2.8.2
4:34:06 PM: + boolean_selector 2.1.0
4:34:06 PM: + browser_launcher 1.0.0
4:34:06 PM: + built_collection 5.1.1
4:34:06 PM: + built_value 8.1.3
4:34:06 PM: + charcode 1.3.1
4:34:06 PM: + checked_yaml 2.0.1
4:34:06 PM: + cli_util 0.3.5
4:34:06 PM: + clock 1.1.0
4:34:06 PM: + collection 1.15.0
4:34:06 PM: + completion 1.0.0
4:34:06 PM: + convert 3.0.1
4:34:06 PM: + coverage 1.0.3 (1.0.4 available)
4:34:06 PM: + crypto 3.0.1
4:34:06 PM: + csslib 0.17.1
4:34:06 PM: + dds 2.1.4 (2.1.7 available)
4:34:06 PM: + devtools_shared 2.8.0 (2.9.2 available)
4:34:06 PM: + dwds 11.5.1
4:34:06 PM: + fake_async 1.2.0
4:34:06 PM: + file 6.1.2
4:34:06 PM: + file_testing 3.0.0
4:34:06 PM: + fixnum 1.0.0
4:34:06 PM: + flutter_template_images 4.0.0
4:34:06 PM: + frontend_server_client 2.1.2
4:34:06 PM: + glob 2.0.2
4:34:06 PM: + html 0.15.0
4:34:06 PM: + http 0.13.4
4:34:06 PM: + http_multi_server 3.0.1
4:34:06 PM: + http_parser 4.0.0
4:34:06 PM: + intl 0.17.0
4:34:06 PM: + io 1.0.3
4:34:06 PM: + js 0.6.3 (0.6.4 available)
4:34:06 PM: + json_annotation 4.4.0
4:34:06 PM: + json_rpc_2 3.0.1
4:34:06 PM: + logging 1.0.2
4:34:06 PM: + matcher 0.12.11
4:34:06 PM: + meta 1.7.0
4:34:06 PM: + mime 1.0.1
4:34:06 PM: + multicast_dns 0.3.1
4:34:06 PM: + mustache_template 2.0.0
4:34:06 PM: + native_stack_traces 0.4.3
4:34:06 PM: + node_preamble 2.0.1
4:34:06 PM: + package_config 2.0.2
4:34:06 PM: + path 1.8.0 (1.8.1 available)
4:34:06 PM: + pedantic 1.11.1 (discontinued replaced by lints)
4:34:06 PM: + petitparser 4.4.0
4:34:06 PM: + platform 3.1.0
4:34:06 PM: + pool 1.5.0
4:34:06 PM: + process 4.2.4
4:34:06 PM: + pub_semver 2.1.0
4:34:06 PM: + pubspec_parse 1.2.0
4:34:06 PM: + shelf 1.1.4 (1.2.0 available)
4:34:06 PM: + shelf_packages_handler 3.0.0
4:34:06 PM: + shelf_proxy 1.0.1
4:34:06 PM: + shelf_static 1.1.0
4:34:06 PM: + shelf_web_socket 1.0.1
4:34:06 PM: + source_map_stack_trace 2.1.0
4:34:06 PM: + source_maps 0.10.10
4:34:06 PM: + source_span 1.8.1
4:34:06 PM: + sse 4.1.0
4:34:06 PM: + stack_trace 1.10.0
4:34:06 PM: + stream_channel 2.1.0
4:34:06 PM: + string_scanner 1.1.0
4:34:06 PM: + sync_http 0.3.0
4:34:06 PM: + term_glyph 1.2.0
4:34:06 PM: + test 1.19.5 (1.20.1 available)
4:34:06 PM: + test_api 0.4.8 (0.4.9 available)
4:34:06 PM: + test_core 0.4.9 (0.4.11 available)
4:34:06 PM: + typed_data 1.3.0
4:34:06 PM: + usage 4.0.2
4:34:06 PM: + uuid 3.0.5
4:34:06 PM: + vm_service 7.5.0 (8.1.0 available)
4:34:06 PM: + vm_snapshot_analysis 0.7.0
4:34:06 PM: + watcher 1.0.1
4:34:06 PM: + web_socket_channel 2.1.0
4:34:06 PM: + webdriver 3.0.0
4:34:06 PM: + webkit_inspection_protocol 1.0.0
4:34:06 PM: + xml 5.3.1
4:34:06 PM: + yaml 3.1.0
4:34:06 PM: Downloading test 1.19.5...
4:34:06 PM: Downloading node_preamble 2.0.1...
4:34:06 PM: Downloading json_annotation 4.4.0...
4:34:06 PM: Downloading js 0.6.3...
4:34:06 PM: Downloading checked_yaml 2.0.1...
4:34:06 PM: Downloading pubspec_parse 1.2.0...
4:34:06 PM: Downloading file_testing 3.0.0...
4:34:06 PM: Downloading collection 1.15.0...
4:34:06 PM: Downloading watcher 1.0.1...
4:34:06 PM: Downloading typed_data 1.3.0...
4:34:06 PM: Downloading term_glyph 1.2.0...
4:34:06 PM: Downloading sync_http 0.3.0...
4:34:06 PM: Downloading string_scanner 1.1.0...
4:34:06 PM: Downloading sse 4.1.0...
4:34:06 PM: Downloading source_span 1.8.1...
4:34:06 PM: Downloading source_maps 0.10.10...
4:34:06 PM: Downloading source_map_stack_trace 2.1.0...
4:34:06 PM: Downloading shelf_proxy 1.0.1...
4:34:06 PM: Downloading shelf_packages_handler 3.0.0...
4:34:06 PM: Downloading platform 3.1.0...
4:34:06 PM: Downloading petitparser 4.4.0...
4:34:06 PM: Downloading pedantic 1.11.1...
4:34:06 PM: Downloading matcher 0.12.11...
4:34:06 PM: Downloading json_rpc_2 3.0.1...
4:34:06 PM: Downloading io 1.0.3...
4:34:06 PM: Downloading http_parser 4.0.0...
4:34:06 PM: Downloading glob 2.0.2...
4:34:06 PM: Downloading frontend_server_client 2.1.2...
4:34:06 PM: Downloading fixnum 1.0.0...
4:34:06 PM: Downloading devtools_shared 2.8.0...
4:34:06 PM: Downloading csslib 0.17.1...
4:34:06 PM: Downloading clock 1.1.0...
4:34:06 PM: Downloading cli_util 0.3.5...
4:34:06 PM: Downloading charcode 1.3.1...
4:34:06 PM: Downloading built_value 8.1.3...
4:34:06 PM: Downloading built_collection 5.1.1...
4:34:06 PM: Downloading boolean_selector 2.1.0...
4:34:06 PM: Downloading analyzer 2.8.0...
4:34:06 PM: Downloading _fe_analyzer_shared 31.0.0...
4:34:06 PM: Downloading vm_service 7.5.0...
4:34:06 PM: Downloading test_core 0.4.9...
4:34:06 PM: Downloading test_api 0.4.8...
4:34:06 PM: Downloading async 2.8.2...
4:34:06 PM: Downloading convert 3.0.1...
4:34:06 PM: Downloading http_multi_server 3.0.1...
4:34:06 PM: Downloading logging 1.0.2...
4:34:06 PM: Downloading mime 1.0.1...
4:34:06 PM: Downloading path 1.8.0...
4:34:06 PM: Downloading pool 1.5.0...
4:34:06 PM: Downloading pub_semver 2.1.0...
4:34:06 PM: Downloading shelf_static 1.1.0...
4:34:06 PM: Downloading shelf_web_socket 1.0.1...
4:34:06 PM: Downloading stream_channel 2.1.0...
4:34:06 PM: Downloading web_socket_channel 2.1.0...
4:34:06 PM: Downloading uuid 3.0.5...
4:34:06 PM: Downloading vm_snapshot_analysis 0.7.0...
4:34:06 PM: Downloading shelf 1.1.4...
4:34:06 PM: Downloading native_stack_traces 0.4.3...
4:34:06 PM: Downloading yaml 3.1.0...
4:34:06 PM: Downloading xml 5.3.1...
4:34:06 PM: Downloading webkit_inspection_protocol 1.0.0...
4:34:06 PM: Downloading webdriver 3.0.0...
4:34:06 PM: Downloading usage 4.0.2...
4:34:06 PM: Downloading stack_trace 1.10.0...
4:34:06 PM: Downloading fake_async 1.2.0...
4:34:06 PM: Downloading process 4.2.4...
4:34:06 PM: Downloading package_config 2.0.2...
4:34:06 PM: Downloading mustache_template 2.0.0...
4:34:06 PM: Downloading multicast_dns 0.3.1...
4:34:06 PM: Downloading meta 1.7.0...
4:34:06 PM: Downloading intl 0.17.0...
4:34:06 PM: Downloading http 0.13.4...
4:34:06 PM: Downloading html 0.15.0...
4:34:06 PM: Downloading flutter_template_images 4.0.0...
4:34:06 PM: Downloading file 6.1.2...
4:34:06 PM: Downloading crypto 3.0.1...
4:34:06 PM: Downloading coverage 1.0.3...
4:34:06 PM: Downloading completion 1.0.0...
4:34:06 PM: Downloading dwds 11.5.1...
4:34:06 PM: Downloading dds 2.1.4...
4:34:06 PM: Downloading browser_launcher 1.0.0...
4:34:06 PM: Downloading args 2.3.0...
4:34:06 PM: Downloading archive 3.1.6...
4:34:13 PM: Changed 83 dependencies!
4:34:13 PM: 1 package is discontinued.
4:34:13 PM: 12 packages have newer versions incompatible with dependency constraints.
4:34:13 PM: Try `dart pub outdated` for more information.
4:35:02 PM:   ╔════════════════════════════════════════════════════════════════════════════╗
4:35:02 PM:   ║                 Welcome to Flutter! - https://flutter.dev                  ║
4:35:02 PM:   ║                                                                            ║
4:35:02 PM:   ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
4:35:02 PM:   ║ statistics and basic crash reports. This data is used to help improve      ║
4:35:02 PM:   ║ Flutter tools over time.                                                   ║
4:35:02 PM:   ║                                                                            ║
4:35:02 PM:   ║ Flutter tool analytics are not sent on the very first run. To disable      ║
4:35:02 PM:   ║ reporting, type 'flutter config --no-analytics'. To display the current    ║
4:35:02 PM:   ║ setting, type 'flutter config'. If you opt out of analytics, an opt-out    ║
4:35:02 PM:   ║ event will be sent, and then no further information will be sent by the    ║
4:35:02 PM:   ║ Flutter tool.                                                              ║
4:35:02 PM:   ║                                                                            ║
4:35:02 PM:   ║ By downloading the Flutter SDK, you agree to the Google Terms of Service.  ║
4:35:02 PM:   ║ Note: The Google Privacy Policy describes how data is handled in this      ║
4:35:02 PM:   ║ service.                                                                   ║
4:35:02 PM:   ║                                                                            ║
4:35:02 PM:   ║ Moreover, Flutter includes the Dart SDK, which may send usage metrics and  ║
4:35:02 PM:   ║ crash reports to Google.                                                   ║
4:35:02 PM:   ║                                                                            ║
4:35:02 PM:   ║ Read about data we send with crash reports:                                ║
4:35:02 PM:   ║ https://flutter.dev/docs/reference/crash-reporting                         ║
4:35:02 PM:   ║                                                                            ║
4:35:02 PM:   ║ See Google's privacy policy:                                               ║
  ║ https://policies.google.com/privacy                                        ║
4:35:02 PM:   ╚════════════════════════════════════════════════════════════════════════════╝
4:35:02 PM: Setting "enable-web" value to "true".
4:35:02 PM: You may need to restart any open editors for them to read new settings.
4:35:04 PM: Downloading Material fonts...                                      696ms
4:35:04 PM: Downloading Gradle Wrapper...                                       11ms
4:35:04 PM: Downloading package sky_engine...                                  181ms
4:35:05 PM: Downloading flutter_patched_sdk tools...                           581ms
4:35:06 PM: Downloading flutter_patched_sdk_product tools...                   461ms
4:35:08 PM: Downloading linux-x64 tools...                                   2,269ms
4:35:09 PM: Downloading linux-x64/font-subset tools...                         136ms
4:35:12 PM: Downloading Web SDK...                                           2,944ms
4:35:15 PM: Downloading CanvasKit...                                           685ms
4:35:51 PM: Running "flutter pub get" in repo...                               35.4s
4:35:52 PM: 💪 Building with sound null safety 💪
4:36:24 PM: Compiling lib/main.dart for the Web...
4:36:24 PM: Target dart2js failed: Exception: lib/screens/main/Doctor/doctor_add_screen.dart:2:8:
4:36:24 PM: Error: Error when reading 'lib/screens/main/doctor/doctor_add_widget.dart': Error reading 'lib/screens/main/doctor/doctor_add_widget.dart'  (No such file or directory)
4:36:24 PM: import 'package:admin/screens/main/doctor/doctor_add_widget.dart';
4:36:24 PM:        ^
4:36:24 PM: lib/screens/main/doctor/doctors_screen.dart:3:8:
4:36:24 PM: Error: Error when reading 'lib/screens/main/Doctor/doctors_widget.dart': Error reading 'lib/screens/main/Doctor/doctors_widget.dart'  (No such file or directory)
4:36:24 PM: import 'package:admin/screens/main/Doctor/doctors_widget.dart';
4:36:24 PM:        ^
4:36:24 PM: lib/screens/main/Doctor/doctor_add_screen.dart:28:22:
4:36:24 PM: Error: The method 'DoctorAddWidget' isn't defined for the class 'DoctorAddScreen'.
 - 'DoctorAddScreen' is from 'package:admin/screens/main/Doctor/doctor_add_screen.dart' ('lib/screens/main/Doctor/doctor_add_screen.dart').
4:36:24 PM:               child: DoctorAddWidget(
4:36:24 PM:                      ^^^^^^^^^^^^^^^
4:36:24 PM: lib/screens/main/doctor/doctors_screen.dart:28:22:
4:36:24 PM: Error: The method 'DoctorsWidget' isn't defined for the class 'DoctorsScreen'.
 - 'DoctorsScreen' is from 'package:admin/screens/main/doctor/doctors_screen.dart' ('lib/screens/main/doctor/doctors_screen.dart').
4:36:24 PM:               child: DoctorsWidget(
4:36:24 PM:                      ^^^^^^^^^^^^^
4:36:24 PM: Error: Compilation failed.
4:36:24 PM: Compiling lib/main.dart for the Web...                             32.0s
4:36:24 PM: Exception: Failed to compile application for the Web.
4:36:24 PM: ​
4:36:24 PM: ────────────────────────────────────────────────────────────────
4:36:24 PM:   "build.command" failed                                        
4:36:24 PM: ────────────────────────────────────────────────────────────────
4:36:24 PM: ​
4:36:24 PM:   Error message
4:36:24 PM:   Command failed with exit code 1: if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
4:36:24 PM: ​
4:36:24 PM:   Error location
4:36:24 PM:   In Build command from Netlify app:
4:36:24 PM:   if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
4:36:24 PM: ​
4:36:24 PM:   Resolved config
4:36:24 PM:   build:
4:36:24 PM:     command: if cd flutter; then git pull && cd ..; else git clone https://github.com/flutter/flutter.git; fi && flutter/bin/flutter config --enable-web && flutter/bin/flutter build web --release --dart-define=FLUTTER_WEB_USE_SKIA=true
4:36:24 PM:     commandOrigin: ui
4:36:24 PM:     publish: /opt/build/repo/build/web
4:36:24 PM:     publishOrigin: ui
4:36:24 PM: Caching artifacts
4:36:24 PM: Started saving build plugins
4:36:24 PM: Finished saving build plugins
4:36:24 PM: Started saving pip cache
4:36:24 PM: Finished saving pip cache
4:36:24 PM: Started saving emacs cask dependencies
4:36:24 PM: Finished saving emacs cask dependencies
4:36:24 PM: Started saving maven dependencies
4:36:24 PM: Finished saving maven dependencies
4:36:24 PM: Started saving boot dependencies
4:36:24 PM: Finished saving boot dependencies
4:36:24 PM: Started saving rust rustup cache
4:36:24 PM: Finished saving rust rustup cache
4:36:24 PM: Started saving go dependencies
4:36:24 PM: Finished saving go dependencies
4:36:27 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
4:36:27 PM: Creating deploy upload records
4:36:27 PM: Failing build: Failed to build site
4:36:27 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
4:36:27 PM: Finished processing build request in 3m5.98873726s
Docs
Pricing
Support
News
Terms
© 2021 Netlify
