### ISSUE TITLE
Support queuing & throttling http requests for image download

### ISSUE THREAD

**Issue by rajveermalviya** [Baseflow/flutter_cached_network_image#453]
## 🚀 Feature Requests

Support queuing & max concurrent http requests for downloading the images.

### Contextualize the feature

This is very important when 10+ CachedNetworkImage widgets are used and shown in UI at the same time.

### Describe the feature

This can be done by using sharing HttpClient across all CachedNetworkImage instances and creating a queuing logic.
Default for browsers is 4-6 max request for http/1 & 100 for http/2.
Though setting a custom count would be ideal.

### Platforms affected (mark all that apply)
- all

**Comment by whatamelon** [comment]
agree

**Comment by vipafattal** [comment]
Actually this very important enhancement, and it becomes a dramatically serious issue when using `CachedNetworkImage` inside a very long `ListView` (with or without pagination) since use can make fast scroll in `ListView` so the `CachedNetworkImage` will be triggered to make a request for each item will be added to the `ListView` so if the user scrolled through all list content.

Imagine the list contains 100 items, the library is loading these requests altogether, which in cases will lead to assign the client as bot by the server (or pending the client).
  
I think that if possible supporting max concurrent connection will forbid that issue.

**Comment by rajveermalviya** [comment]
@vipafattal , this has already been implemented in
 [Baseflow/flutter_cache_manager#234](https://github.com/Baseflow/flutter_cache_manager/pull/234).

So, you shouldn't have this issue anymore.
