### ISSUE TITLE
Cached Failed

### ISSUE THREAD

**Issue by carmas123** [Baseflow/flutter_cached_network_image#455]
Hi, there is an option to skip caching the failed images download?

**Comment by renefloor** [comment]
Do you mean in the memory ImageCache of Flutter or the caching on disk?
If you mean the ImageCache it is a duplicate of this issue: https://github.com/Baseflow/flutter_cached_network_image/issues/451
Otherwise you need to explain a bit better, because failed downloads are not cached, because there is nothing to cache.
