### ISSUE TITLE
io.flutter.1.ui: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by DizzyYang** [Baseflow/flutter_cached_network_image#635]
## 🐛 Bug Report

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.4.0-4.2.pre, on macOS 11.5 20G71 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] Connected device (2 available)

• No issues found!

Refresh component usage: pull_to_refresh
Image loading: cached_network_image

A crash occurs when the quick slide bottom loads more data and returns 100 pieces (including pictures).
io.flutter.1.ui: EXC_BAD_ACCESS

When I load and remove the picture, there will be no crash.

**Version:** 3.1.0

**Platform:** 
- [✔️] :iphone: iOS

**Comment by Klabauterman** [comment]
I have the same issue (Version 3.2.0). I only have a long list of cells that contain 1 image each. The crash happens when I scroll very fast through the cells. It looks like when I scroll carefully through the whole list the first time so that all Images are cached. It does not crash the next time I scroll fast.
But when I clear the cache using DefaultCacheManager().emptyCache(); and then scroll very fast through the list, it crashes 100% of the time.
