### ISSUE TITLE
How to update image with same URL

### ISSUE THREAD

**Issue by codepushr** [Baseflow/flutter_cached_network_image#650]
Hi,

just to confirm: there is no built in way for the library to display an old cache and automatically fetching a newer version of an image with the same URL and replace it if needed?

Example:
Displaying a company logo which has the same static URL /api/company/1/avatar.jpg.
I can replace the image but the URL stays the same.

What I want is to display the older version initially while updating it with the new version.

How would I use this library for this matter?

**Comment by renefloor** [comment]
It does this actually. It uses [cache-control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) headers to know if the cache is outdated (max-age and eTag). If it is outdated the cached version is shown directly and the server is requested for an update. If the server sends a new image it updates the image directly. [That's why the caching is a stream here.](https://github.com/Baseflow/flutter_cached_network_image/blob/develop/cached_network_image/lib/src/image_provider/_image_loader.dart#L49) At the moment there is no option to force an update when the cache is not yet outdated.

**Comment by codepushr** [comment]
Yes. Thanks a bunch!

**Comment by cedvdb** [comment]
What could be the reason for an etag that changes but not the image ? I need to refresh the page to actually see the change

**Comment by cedvdb** [comment]
The issue is because cachedNetworkImage does not support web, it works fine on android

**Comment by justChris** [comment]
@renefloor Your first answer actually describes my expected behavior. But when I update an image behind the same url, the server (firebase storage) sends a changed etag and last-modified header, but flutter_cached_network_image will not refetch the image or will not update the cache. However I do not see the updated image in the app. (iOS and android).
