### ISSUE TITLE
Error: The getter 'utrethrow' isn't defined for the class 'ImageLoader'.

### ISSUE THREAD

**Issue by waheedhaans** [Baseflow/flutter_cached_network_image#770]
## 🐛 Bug Report
../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.1/lib/src/image_provider/_image_loader.dart:72:7: Error: The getter 'utrethrow' isn't defined for the class 'ImageLoader'.
 - 'ImageLoader' is from 'package:cached_network_image/src/image_provider/_image_loader.dart' ('../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.1/lib/src/image_provider/_image_loader.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'utrethrow'.
      utrethrow;

### Reproduction steps
Running the project 
### Configuration

**Version:** 3.2.1

**Platform:** 
-  :iphone: iOS

**Comment by Fethi-Hamdani** [comment]
/C:/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.2/lib/src/image_provider/_image_loader.dart:125:7: Error: The getter 'orrethrow' isn't defined for the class 'ImageLoader'.

- 'ImageLoader' is from 'package:cached_network_image/src/image_provider/_image_loader.dart' ('/C:/Development/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.2/lib/src/image_provider/_image_loader.dart').
package:cached_network_image/…/image_provider/_image_loader.dart:1
Script 'C:\Development\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1159
Execution failed for task ':app:compileFlutterBuildStagingDebug'.

i'm getting the same issue but it says 'orrethrow' instead of  'utrethrow'

Reproduction steps
Running the project

Configuration
Version: 3.2.2

Platform:
📱 Android

**Comment by datvu1907** [comment]
../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/_image_loader.dart:72:7: Error: The getter 'nirethrow' isn't defined for the class 'ImageLoader'.
 - 'ImageLoader' is from 'package:cached_network_image/src/image_provider/_image_loader.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/cached_network_image-3.2.0/lib/src/image_provider/_image_loader.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'nirethrow'.
      nirethrow;
      ^^^^^^^^^
      Configuration
Version: 3.2.0

Platform: IOS
